name: "Build and push to dockerhub"

on:
  push:
    branches:
      - master
jobs:
  checking-nodejs:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup nodejs v18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: install dependencies
        run: npm install

      - name: run application
        run: npm start
        